export const stylePortfolio = {
  sectionPortfolio: "relative flex flex-col pb-52 w-full h-auto px-0 bg-[var(--background-dark)]",
  portfolioContent: " flex flex-wrap justify-around max-w-screen-2xl w-full max-lg:w-full w-[90%] items-center text-primary-light relative m-auto max-md:flex-col-reverse max-md:gap-10 ",
  portfolioContentInfo: "flex flex-col w-1/2 h-auto overflow-x-hidden overflow-y-auto max-md:w-[90%]  ",
  portfolioTitleContainer: " flex w-full px-2",
  portfolioTitle: " text-[32px] text-primary-light max-sm:font-normal max-sm:text-xl font-normal leading-9 [font-family:'Philosopher',sans-serif] mb-[28px] relative ",
  portfolioTitleSpan: " relative",
  portfolioTitleSpanBefore: " before:content-['_'] before:absolute before:top-[-7px] before:w-[70px] before:h-[7px] before:bg-primary before:text-[inherit] before:[font-family:'Philosopher',sans-serif] before:rounded-[14px_0_0_14px]",
  btnRepository: " flex flex-col items-center gap-[7px] font-medium text-base max-sm:text-xs",
  faGithubicon: " w-20 h-20 text-primary-light p-1 rounded-[14px] border-2 border-solid border-primary-bord",
  portfolioTextContent: " w-full text-quaternary-light mb-[35px] ",
  portfolioTextTitle: " text-xl text-primary-light font-normal px-2 [font-family:'Kodchasan',sans-serif]",
  portfolioTextSubTitle: " text-lg text-secondary-light [font-family:'Kodchasan',sans-serif] before:check",
  portfolioText: " text-sm ",
  displayNone: " hidden",
  textMore: " overflow-hidden animate-[hideText_2s_ease-in-out_both]",
  portfolioBtnContainer: " flex justify-between w-[48%] gap-[30px] absolute bottom-[-49px] mt-[21px] max-md:w-full max-md:left-0 max-md:px-4 max-md:gap-5",
  btn: " flex justify-center items-center [background:transparent] text-primary-light h-[42px] w-[210px] text-[17px] font-semibold uppercase cursor-pointer rounded-[21px] border-2 border-solid border-secondary-bord",
  wrapImg: " max-w-[400px] min-w-[360px] h-[500px] max-sm:h-[calc(100vw_/_2)] [transform-style:preserve-3d] [perspective:800px] max-md:max-w-[700px] max-md:w-[90%] max-md:min-w-[300px] ",
  portfolioImage: " w-full h-[500px] overflow-hidden shadow-[0_0_14px_7px_rgba(0,0,0,0145)] absolute [transform:rotateY(-7deg)] rounded-[5px] max-md:[transform:rotateY(0deg)]  ",
  portfolioImageImg: " relative w-full h-auto max-sm:h-[calc(100vw_/_2)] shadow-[0_0_21px_4px_rgba(0,0,0,0786)] bottom-0",
  beforeAfterRetangule: " before:content-[''] before:w-[2000px] before:h-[800px] before:absolute before:bg-tertiary-dark-linear before:-z-10 before:rotate-[45deg] before:rounded-3xl before:bottom-[-275%] before:left-[calc(55%)] before:translate-x-[0%] after:content-[''] after:w-[2000px] after:h-[800px] after:absolute after:bg-tertiary-dark-linear after:-z-10 after:rotate-[45deg] after:rounded-3xl after:bottom-[-225%] after:right-[calc(55%)] after:translate-x-[0%]",
}