import type { Metadata } from "next";
import Script from 'next/script'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <Script src="https://cdn.rawgit.com/progers/pathseg/master/pathseg.js"/> */}
      </head>
      <body>{children}</body>
    </html>
  );
}
