import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer/footer";
import { Header } from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className="flex flex-col min-h-screen w-full overflow-x-hidden">
        <Header />
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
